CREATE TABLE STRATEGY (name VARCHAR(255) PRIMARY KEY, class_name VARCHAR(255)) ;
CREATE TABLE INTERVENTION (id INT AUTO_INCREMENT PRIMARY KEY, trial_name VARCHAR(255) UNIQUE NOT NULL, strategy_id VARCHAR(255) NOT NULL REFERENCES STRATEGY(name), cluster_factors VARCHAR(255) NOT NULL) ;
CREATE TABLE ATTRIBUTE(id INT AUTO_INCREMENT PRIMARY KEY, trial_definition_id INT NOT NULL  REFERENCES INTERVENTION(id), attr_name VARCHAR(255) NOT NULL, weight FLOAT NOT NULL, grouping_factor VARCHAR(255), num_groups INT );
CREATE TABLE GROUPS(id INT AUTO_INCREMENT PRIMARY KEY,  attribute_id INT NOT NULL REFERENCES ATTRIBUTE(id), name VARCHAR(255) NOT NULL, range_min FLOAT NOT NULL, range_max FLOAT NOT NULL );
CREATE TABLE TREATMENT(id INT AUTO_INCREMENT PRIMARY KEY, trial_definition_id INT NOT NULL  REFERENCES INTERVENTION(id),  name VARCHAR(255) NOT NULL, weight INT NOT NULL, max_participants INT NOT NULL, participant_limit VARCHAR(255) NOT NULL );
CREATE TABLE INTERVENTION_PARAMS(id INT AUTO_INCREMENT PRIMARY KEY, trial_definition_id INT NOT NULL  REFERENCES INTERVENTION(id), name VARCHAR(255) NOT NULL,  value FLOAT NOT NULL )    ;
CREATE TABLE STRATEGY_STATISTICS(id INT AUTO_INCREMENT PRIMARY KEY, statistic_name VARCHAR(255) NOT NULL, value FLOAT NOT NULL, trial_definition_id INT NOT NULL  REFERENCES INTERVENTION(id));
CREATE TABLE PARTICIPANT(id INT AUTO_INCREMENT PRIMARY KEY, given_id INT, treatment_id INT NOT NULL REFERENCES TREATMENT(id));
CREATE TABLE RESPONSE (id INT AUTO_INCREMENT PRIMARY KEY, value FLOAT NOT NULL, parameter_name VARCHAR(255) NOT NULL, participant_id INT NOT NULL REFERENCES PARTICIPANT(id), time_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, trial_definition_id INT NOT NULL REFERENCES INTERVENTION(id));
